### ISSUE TITLE
As a User, I want to be able to create a new timer from my homepage.

### ISSUE THREAD

**Issue by amantasel** [benevolentprof/fahnlayla#3] opened 2017-12-11 19:00 UTC
The Create New Timer button will always appear a the top of all the timers on the home page. 
Please refer to Zeplin for reference: zpl.io/adRn0xe 

Feature: Create a timer from the homepage

**Scenario 1**: I am a user and I want to create a new timer

* Given I am logged in
   And I am on the homepage

* When I click the create a timer button

* Then I am directed to the create a timer page.

**Comment by whitecat** [comment] 2018-01-10 14:07
1 day. Should be competed before #2

**Comment by amantasel** [comment] 2018-05-02 14:14
![Screen Shot 2018-05-02 at 10.05.17 AM.png](https://images.zenhubusercontent.com/5ae8af024b5806bc2bd15b7f/0aa51dc2-1a6b-467a-a763-87a99057a9f1)

**Comment by benevolentprof** [comment] 2018-05-08 18:47
Closed. Duplicate of #23

**Closed as completed** 2018-05-08 18:46 UTC
